services:
  postgres:
    container_name: postgres_sql
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skills_lab_academy_network

  api:
    container_name: spring_api
    image: skills_lab_academy_api:1.0
    build: ./api
    depends_on:
      - postgres
    environment:
      ADDRESS:
      PORT:
      DB_SCHEMA:
      DB_USERNAME:
      DB_PASSWORD:
      DB_URL:
      CLIENT_URL:
      SECRET_KEY:
      TOKEN_EXPIRATION:
    ports:
      - "1337:1337"
    networks:
      - skills_lab_academy_network


volumes:
  postgres_data:


networks:
  skills_lab_academy_network:
    driver: bridge