eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

name:
  value: pichborith

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  cloud:
    config:
      override-system-properties: false
      import: optional:file:.env[.properties]
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS