server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
#    registerWithEureka: false
    fetch-registry: false
#    fetchRegistry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}/${server.port}/eureka/
#    serviceUrl:
#        defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/