server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/users/**
#          filters:
#            - StripPrefix=1
        - id: course-service
          uri: lb:http://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**
