server:
  port: 8090

  spring:
    data:
      mongodb:
        username: admin
        password: password
        host: localhost
        port: 27017
        database: skills-flask
        authentication-database: admin