services:
  postgres:
    container_name: postgres_sql
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: skills-flask
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skills-flask-app-network

  mongodb:
    container_name: mongo_db
    image: mongo:jammy
    volumes:
      - mongo_data:/var/lib/mongodb/data
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - skills-flask-app-network


volumes:
  postgres_data:
  mongo_data:


networks:
  skills-flask-app-network:
    driver: bridge