server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
